//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PowerPMAC IDE.
//     Date: 6/8/2026, Time: 1:01 AM
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Slave_1001 [NX-ECC203] Station Address-1001
#define Slave_1001_NX_ECC203_Index 0

// Inputs
#define Slave_1001_NX_ECC203_3003_3_NXUnitRegistrationStatus63(x) pshm->ECAT[0].IOBuffer[0 + x]
#define Slave_1001_NX_ECC203_3006_3_NXUnitIODataActiveStatus63(x) pshm->ECAT[0].IOBuffer[8 + x]
#define Slave_1001_NX_ECC203_2002_1_SysmacErrorStatus pshm->ECAT[0].IO[4098].Data
#define Slave_1001_NX_ECC203_6002_1_InputBit16bits pshm->ECAT[0].IO[4099].Data
#define Slave_1001_NX_ECC203_6022_1_InputBit16bits pshm->ECAT[0].IO[4100].Data
#define Slave_1001_NX_ECC203_6080_1_Ch1AnalogInputValue pshm->ECAT[0].IO[4101].Data
#define Slave_1001_NX_ECC203_6080_2_Ch2AnalogInputValue pshm->ECAT[0].IO[4102].Data
#define Slave_1001_NX_ECC203_6080_3_Ch3AnalogInputValue pshm->ECAT[0].IO[4103].Data
#define Slave_1001_NX_ECC203_6080_4_Ch4AnalogInputValue pshm->ECAT[0].IO[4104].Data
#define Slave_1001_NX_ECC203_60A1_1_Ch1MeasuredValueINT pshm->ECAT[0].IO[4105].Data
#define Slave_1001_NX_ECC203_60A1_2_Ch2MeasuredValueINT pshm->ECAT[0].IO[4106].Data

// Outputs
#define Slave_1001_NX_ECC203_7042_1_OutputBit16bits pshm->ECAT[0].IO[0].Data
#define Slave_1001_NX_ECC203_7062_1_OutputBit16bits pshm->ECAT[0].IO[1].Data

// Slave_1002 [MADLN15BL] Station Address-1002
#define Slave_1002_MADLN15BL_Index 1

// Inputs
#define Slave_1002_MADLN15BL_603F_0_Errorcode pshm->ECAT[0].IO[4107].Data
#define Slave_1002_MADLN15BL_6041_0_Statusword pshm->ECAT[0].IO[4108].Data
#define Slave_1002_MADLN15BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4109].Data
#define Slave_1002_MADLN15BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4110].Data
#define Slave_1002_MADLN15BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4111].Data
#define Slave_1002_MADLN15BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4112].Data
#define Slave_1002_MADLN15BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4113].Data
#define Slave_1002_MADLN15BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4114].Data
#define Slave_1002_MADLN15BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4115].Data

// Outputs
#define Slave_1002_MADLN15BL_6040_0_Controlword pshm->ECAT[0].IO[2].Data
#define Slave_1002_MADLN15BL_6060_0_Modesofoperation pshm->ECAT[0].IO[3].Data
#define Slave_1002_MADLN15BL_607A_0_Targetposition pshm->ECAT[0].IO[4].Data
#define Slave_1002_MADLN15BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[5].Data

// Slave_1003 [MADLN15BL] Station Address-1003
#define Slave_1003_MADLN15BL_Index 2

// Inputs
#define Slave_1003_MADLN15BL_603F_0_Errorcode pshm->ECAT[0].IO[4116].Data
#define Slave_1003_MADLN15BL_6041_0_Statusword pshm->ECAT[0].IO[4117].Data
#define Slave_1003_MADLN15BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4118].Data
#define Slave_1003_MADLN15BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4119].Data
#define Slave_1003_MADLN15BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4120].Data
#define Slave_1003_MADLN15BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4121].Data
#define Slave_1003_MADLN15BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4122].Data
#define Slave_1003_MADLN15BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4123].Data
#define Slave_1003_MADLN15BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4124].Data

// Outputs
#define Slave_1003_MADLN15BL_6040_0_Controlword pshm->ECAT[0].IO[6].Data
#define Slave_1003_MADLN15BL_6060_0_Modesofoperation pshm->ECAT[0].IO[7].Data
#define Slave_1003_MADLN15BL_607A_0_Targetposition pshm->ECAT[0].IO[8].Data
#define Slave_1003_MADLN15BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[9].Data

// Slave_1004 [MCDLN35BL] Station Address-1004
#define Slave_1004_MCDLN35BL_Index 3

// Inputs
#define Slave_1004_MCDLN35BL_603F_0_Errorcode pshm->ECAT[0].IO[4125].Data
#define Slave_1004_MCDLN35BL_6041_0_Statusword pshm->ECAT[0].IO[4126].Data
#define Slave_1004_MCDLN35BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4127].Data
#define Slave_1004_MCDLN35BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4128].Data
#define Slave_1004_MCDLN35BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4129].Data
#define Slave_1004_MCDLN35BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4130].Data
#define Slave_1004_MCDLN35BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4131].Data
#define Slave_1004_MCDLN35BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4132].Data
#define Slave_1004_MCDLN35BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4133].Data

// Outputs
#define Slave_1004_MCDLN35BL_6040_0_Controlword pshm->ECAT[0].IO[10].Data
#define Slave_1004_MCDLN35BL_6060_0_Modesofoperation pshm->ECAT[0].IO[11].Data
#define Slave_1004_MCDLN35BL_607A_0_Targetposition pshm->ECAT[0].IO[12].Data
#define Slave_1004_MCDLN35BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[13].Data

// Slave_1005 [MBDLN25BE] Station Address-1005
#define Slave_1005_MBDLN25BE_Index 4

// Inputs
#define Slave_1005_MBDLN25BE_603F_0_Errorcode pshm->ECAT[0].IO[4134].Data
#define Slave_1005_MBDLN25BE_6041_0_Statusword pshm->ECAT[0].IO[4135].Data
#define Slave_1005_MBDLN25BE_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4136].Data
#define Slave_1005_MBDLN25BE_6064_0_Positionactualvalue pshm->ECAT[0].IO[4137].Data
#define Slave_1005_MBDLN25BE_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4138].Data
#define Slave_1005_MBDLN25BE_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4139].Data
#define Slave_1005_MBDLN25BE_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4140].Data
#define Slave_1005_MBDLN25BE_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4141].Data
#define Slave_1005_MBDLN25BE_60FD_0_Digitalinputs pshm->ECAT[0].IO[4142].Data

// Outputs
#define Slave_1005_MBDLN25BE_6040_0_Controlword pshm->ECAT[0].IO[14].Data
#define Slave_1005_MBDLN25BE_6060_0_Modesofoperation pshm->ECAT[0].IO[15].Data
#define Slave_1005_MBDLN25BE_607A_0_Targetposition pshm->ECAT[0].IO[16].Data
#define Slave_1005_MBDLN25BE_60B8_0_Touchprobefunction pshm->ECAT[0].IO[17].Data

// Slave_1006 [MADLN15BL] Station Address-1006
#define Slave_1006_MADLN15BL_Index 5

// Inputs
#define Slave_1006_MADLN15BL_603F_0_Errorcode pshm->ECAT[0].IO[4143].Data
#define Slave_1006_MADLN15BL_6041_0_Statusword pshm->ECAT[0].IO[4144].Data
#define Slave_1006_MADLN15BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4145].Data
#define Slave_1006_MADLN15BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4146].Data
#define Slave_1006_MADLN15BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4147].Data
#define Slave_1006_MADLN15BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4148].Data
#define Slave_1006_MADLN15BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4149].Data
#define Slave_1006_MADLN15BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4150].Data
#define Slave_1006_MADLN15BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4151].Data

// Outputs
#define Slave_1006_MADLN15BL_6040_0_Controlword pshm->ECAT[0].IO[18].Data
#define Slave_1006_MADLN15BL_6060_0_Modesofoperation pshm->ECAT[0].IO[19].Data
#define Slave_1006_MADLN15BL_607A_0_Targetposition pshm->ECAT[0].IO[20].Data
#define Slave_1006_MADLN15BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[21].Data

// Slave_1007 [MADLN15BL] Station Address-1007
#define Slave_1007_MADLN15BL_Index 6

// Inputs
#define Slave_1007_MADLN15BL_603F_0_Errorcode pshm->ECAT[0].IO[4152].Data
#define Slave_1007_MADLN15BL_6041_0_Statusword pshm->ECAT[0].IO[4153].Data
#define Slave_1007_MADLN15BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4154].Data
#define Slave_1007_MADLN15BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4155].Data
#define Slave_1007_MADLN15BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4156].Data
#define Slave_1007_MADLN15BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4157].Data
#define Slave_1007_MADLN15BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4158].Data
#define Slave_1007_MADLN15BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4159].Data
#define Slave_1007_MADLN15BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4160].Data

// Outputs
#define Slave_1007_MADLN15BL_6040_0_Controlword pshm->ECAT[0].IO[22].Data
#define Slave_1007_MADLN15BL_6060_0_Modesofoperation pshm->ECAT[0].IO[23].Data
#define Slave_1007_MADLN15BL_607A_0_Targetposition pshm->ECAT[0].IO[24].Data
#define Slave_1007_MADLN15BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[25].Data

// Slave_1008 [MCDLN35BL] Station Address-1008
#define Slave_1008_MCDLN35BL_Index 7

// Inputs
#define Slave_1008_MCDLN35BL_603F_0_Errorcode pshm->ECAT[0].IO[4161].Data
#define Slave_1008_MCDLN35BL_6041_0_Statusword pshm->ECAT[0].IO[4162].Data
#define Slave_1008_MCDLN35BL_6061_0_Modesofoperationdisplay pshm->ECAT[0].IO[4163].Data
#define Slave_1008_MCDLN35BL_6064_0_Positionactualvalue pshm->ECAT[0].IO[4164].Data
#define Slave_1008_MCDLN35BL_606C_0_Velocityactualvalue pshm->ECAT[0].IO[4165].Data
#define Slave_1008_MCDLN35BL_6077_0_Torqueactualvalue pshm->ECAT[0].IO[4166].Data
#define Slave_1008_MCDLN35BL_60B9_0_Touchprobestatus pshm->ECAT[0].IO[4167].Data
#define Slave_1008_MCDLN35BL_60BA_0_Touchprobepos1posvalue pshm->ECAT[0].IO[4168].Data
#define Slave_1008_MCDLN35BL_60FD_0_Digitalinputs pshm->ECAT[0].IO[4169].Data

// Outputs
#define Slave_1008_MCDLN35BL_6040_0_Controlword pshm->ECAT[0].IO[26].Data
#define Slave_1008_MCDLN35BL_6060_0_Modesofoperation pshm->ECAT[0].IO[27].Data
#define Slave_1008_MCDLN35BL_607A_0_Targetposition pshm->ECAT[0].IO[28].Data
#define Slave_1008_MCDLN35BL_60B8_0_Touchprobefunction pshm->ECAT[0].IO[29].Data

// Slave_1009 [JXCE1] Station Address-1009
#define Slave_1009_JXCE1_Index 8

// Inputs
#define Slave_1009_JXCE1_6010_0_Signalallocatedtotheinputport pshm->ECAT[0].IO[4170].Data
#define Slave_1009_JXCE1_6011_0_Controllerinformationflag pshm->ECAT[0].IO[4171].Data
#define Slave_1009_JXCE1_6020_0_Currentposition pshm->ECAT[0].IO[4172].Data
#define Slave_1009_JXCE1_6021_0_Currentspeed pshm->ECAT[0].IO[4173].Data
#define Slave_1009_JXCE1_6022_0_Currentpushingforce pshm->ECAT[0].IO[4174].Data
#define Slave_1009_JXCE1_6023_0_Targetposition pshm->ECAT[0].IO[4175].Data
#define Slave_1009_JXCE1_6030_1_Alarm1 pshm->ECAT[0].IO[4176].Data
#define Slave_1009_JXCE1_6030_2_Alarm2 pshm->ECAT[0].IO[4177].Data
#define Slave_1009_JXCE1_6030_3_Alarm3 pshm->ECAT[0].IO[4178].Data
#define Slave_1009_JXCE1_6030_4_Alarm4 pshm->ECAT[0].IO[4179].Data

// Outputs
#define Slave_1009_JXCE1_7010_0_Outputporttowhichsignalsareallocated pshm->ECAT[0].IO[30].Data
#define Slave_1009_JXCE1_7011_0_Controllingofthenumericaldataflag pshm->ECAT[0].IO[31].Data
#define Slave_1009_JXCE1_7012_0_Startflag pshm->ECAT[0].IO[32].Data
#define Slave_1009_JXCE1_7020_0_OperationMethod pshm->ECAT[0].IO[33].Data
#define Slave_1009_JXCE1_7021_0_Speed pshm->ECAT[0].IO[34].Data
#define Slave_1009_JXCE1_7022_0_Targetposition pshm->ECAT[0].IO[35].Data
#define Slave_1009_JXCE1_7023_0_Acceleration pshm->ECAT[0].IO[36].Data
#define Slave_1009_JXCE1_7024_0_Deceleration pshm->ECAT[0].IO[37].Data
#define Slave_1009_JXCE1_7025_0_Pushingforce pshm->ECAT[0].IO[38].Data
#define Slave_1009_JXCE1_7026_0_TriggerLV pshm->ECAT[0].IO[39].Data
#define Slave_1009_JXCE1_7027_0_Pushingspeed pshm->ECAT[0].IO[40].Data
#define Slave_1009_JXCE1_7028_0_Pushingforceforpositioning pshm->ECAT[0].IO[41].Data
#define Slave_1009_JXCE1_7029_0_AREA1 pshm->ECAT[0].IO[42].Data
#define Slave_1009_JXCE1_702A_0_AREA2 pshm->ECAT[0].IO[43].Data
#define Slave_1009_JXCE1_702B_0_Positioningwidth pshm->ECAT[0].IO[44].Data
