# This section loads all Power PMAC programs & is run through the pre-processor/CmdProcessor. It is a sample project default load.



[PMAC_BUFFERS]
TableBufSize=1048576
UserBufSize=1048576
LookAheadBufSize=16777216
ProgramBufSize=16777216
SymbolsBufSize=1048576

[CPU_AFFINITY]
gatecapturetask=1
phasetask=1
servotask=1
rtitask=2
rticplcthread=2
backgroundthread=0
ecattask=3
eiptask=0
gpascii=0
bgcplcthread=0

[THREAD_PRIORITY]
BackgroundThread=10
EthercatThread=97

[PMACMODE]
UserMode=0
verbose=0

[ETHERCAT]
EcatType=1

[IEC61131]
name=
number=

[CUSTOM_CONFIG_FILE]

[MACRO_STATIONS]
[PROJECT_SETTINGS]
runatpc=0
[CPLCC]
LibraryDir=/var/ftp/usrflash/Project/Bin/Debug/
[PMAC_PROGRAMS]
PVARSTART=8192
QVARSTART=1024
MVARSTART=8192
file1=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/ECATMap.pmh
file2=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/AX1515_Mapping.pmh
file3=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H00_Setup_System.pmh
file4=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H01_Setup_EncTable.pmh
file5=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H02_Setup_Motor.pmh
file6=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H03_Setup_Coord.pmh
file7=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H04_Setup_Ecat.pmh
file8=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H05_Setup_Gpio.pmh
file9=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H06_Variable_Umem.pmh
file10=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H07_Variable_UmemArray.pmh
file11=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H08_Variable_Prog.pmh
file12=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H09_Kinematics.pmh
file13=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/H10_Nc.pmh
file14=/var/ftp/usrflash/Project/PMAC Script Language/Global Includes/AX1515_0_Mapping.pmh
file15=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Forward1.kin
file16=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Inverse1.kin
file17=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Forward2.kin
file18=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Inverse2.kin
file19=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Forward3.kin
file20=/var/ftp/usrflash/Project/PMAC Script Language/Kinematic Routines/Inverse3.kin
file21=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/timer.pmc
file22=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_Gcode.pmc
file23=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_Mcode.pmc
file24=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_AbortVsHome.pmc
file25=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_AbortVsLoop.pmc
file26=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_AbortWsHome.pmc
file27=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_AbortWsLoop.pmc
file28=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_InitCommand.pmc
file29=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_InitECylinder.pmc
file30=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_InitMotor.pmc
file31=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_InitScanner.pmc
file32=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_InitSeqParam.pmc
file33=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetDefaultParam.pmc
file34=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetEquOut.pmc
file35=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetSeqBufQ.pmc
file36=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsLdParam.pmc
file37=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsRdParam.pmc
file38=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsRjParam.pmc
file39=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsUdParam.pmc
file40=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsVnParam.pmc
file41=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetVsWtParam.pmc
file42=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsLdParam.pmc
file43=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsRdParam.pmc
file44=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsRjParam.pmc
file45=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsUdParam.pmc
file46=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsWdParam.pmc
file47=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_SetWsWtParam.pmc
file48=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_ReadScPos.pmc
file49=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_ResetVsAlarm.pmc
file50=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_ResetWsAlarm.pmc
file51=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_ReadThPos.pmc
file52=/var/ftp/usrflash/Project/PMAC Script Language/Libraries/SPG_ConvertFunc.pmc
file53=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG01_Test1.pmc
file54=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG02_Test2.pmc
file55=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG03_Test3.pmc
file56=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG04_Test4.pmc
file57=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG05_Test5.pmc
file58=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG19_Zero.pmc
file59=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG20_Welding.pmc
file60=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG21_Circle.pmc
file61=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG22_SnowMan.pmc
file62=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG23_ButterFly.pmc
file63=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG24_Column.pmc
file64=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG25_Row.pmc
file65=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG30_Vision.pmc
file66=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG50_LaserTest_Cross.pmc
file67=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG51_LaserTest_Line.pmc
file68=/var/ftp/usrflash/Project/PMAC Script Language/Motion Programs/PRG18_ProgMove.pmc
file69=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC00_RTI.plc
file70=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC01_Init.plc
file71=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC02_Sta.plc
file72=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC03_Cmd.plc
file73=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC04_Safety.plc
file74=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC05_Ecat.plc
file75=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC06_IoCom.plc
file76=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC10_Home.plc
file77=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC11_Jog.plc
file78=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC12_SeqMc.plc
file79=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC13_SeqWs.plc
file80=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC14_SeqVs.plc
file81=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC20_Cylinder.plc
file82=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC21_TestShot.plc
file83=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC22_LaserCtrl.plc
file84=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC23_TargetMove.plc
file85=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC24_Cover.plc
file86=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC25_BlowOff.plc
file87=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC27_PickAndPlace.plc
file88=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC28_VisionTrigger.plc
file89=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC29_Buf.plc
file90=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC30_Test.plc
file91=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC31_ReqSim.plc
file92=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC26_PowerCheck.plc
file93=/var/ftp/usrflash/Project/PMAC Script Language/PLC Programs/PLC32_VisionSeq.plc
last_file_number=93
[LINUX_PROGRAMS]
program1=/var/ftp/usrflash/Project/C Language/Background Programs/capp1.out
run1=0
last_program_number=1
[RTUSRCCODE]
usrrtmodule=/var/ftp/usrflash/Project/Bin/Debug/usralgo.ko
